# Generated by Django 5.2.5 on 2025-10-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SQL Injection', 'SQL Injection'), ('Brute-Force', 'Brute-Force'), ('Cryptography', 'Cryptography'), ('XSS', 'XSS'), ('CSRF', 'CSRF'), ('NoSQL Injection', 'NoSQL Injection'), ('SSTI', 'SSTI'), ('Command Injection', 'Command Injection'), ('Prompt Injection', 'Prompt Injection'), ('Data Poisoning', 'Data Poisoning'), ('Model Theft', 'Model Theft')], max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
        ),
    ]
