# Generated by Django 5.2.6 on 2026-04-02 18:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_customuser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pics/default.png', max_length=255, verbose_name='image'),
        ),
    ]
